package com.dicka.entities;
// Generated Feb 28, 2017 8:39:59 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="db_product"
)
public class Product  implements java.io.Serializable {


     private String idproduct;
     private Categories categories;
     private String nama;
     private BigDecimal price;
     private int qty;

    public Product() {
    }

    public Product(String idproduct, Categories categories, String nama, BigDecimal price, int qty) {
       this.idproduct = idproduct;
       this.categories = categories;
       this.nama = nama;
       this.price = price;
       this.qty = qty;
    }
   
     @Id 

    
    @Column(name="idproduct", unique=true, nullable=false)
    public String getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(String idproduct) {
        this.idproduct = idproduct;
    }

@ManyToOne
    @JoinColumn(name="idcategoris", nullable=false)
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="nama", nullable=false)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="price", nullable=false, precision=5, scale=3)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="qty", nullable=false)
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }




}


